# Generated by Django 5.0 on 2023-12-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_password_alter_user_username_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
