# Generated by Django 5.0 on 2024-01-03 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
