# Generated by Django 5.0 on 2024-01-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('ready_for_pickup', 'Ready for Pickup'), ('picked_up', 'Picked Up'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20),
        ),
    ]
